//===----------------------------------------------------------------------===//
// GENERATED by viceroy-tablegen from vendor/whatwg — DO NOT EDIT BY HAND.
// Regenerate with: swift run viceroy-tablegen
//===----------------------------------------------------------------------===//
#if SingleByte
extension Encoding {
    /// IBM866, resolved statically — links only the single-byte tables.
    public enum IBM866: TextEncoding {
        public static var name: String { "IBM866" }

        public static func decode(_ bytes: [UInt8], mode: DecodingErrorMode) throws(ViceroyError) -> String {
            try runDecode(SingleByteDecoder(tableIndex: 0), bytes, mode, stripBOM: false)
        }

        public static func encode(_ string: String, mode: EncodingErrorMode) throws(ViceroyError) -> [UInt8] {
            try runEncode(SingleByteEncoder(tableIndex: 0), string.unicodeScalars, mode)
        }
    }

    /// ISO-8859-2, resolved statically — links only the single-byte tables.
    public enum ISO8859_2: TextEncoding {
        public static var name: String { "ISO-8859-2" }

        public static func decode(_ bytes: [UInt8], mode: DecodingErrorMode) throws(ViceroyError) -> String {
            try runDecode(SingleByteDecoder(tableIndex: 1), bytes, mode, stripBOM: false)
        }

        public static func encode(_ string: String, mode: EncodingErrorMode) throws(ViceroyError) -> [UInt8] {
            try runEncode(SingleByteEncoder(tableIndex: 1), string.unicodeScalars, mode)
        }
    }

    /// ISO-8859-3, resolved statically — links only the single-byte tables.
    public enum ISO8859_3: TextEncoding {
        public static var name: String { "ISO-8859-3" }

        public static func decode(_ bytes: [UInt8], mode: DecodingErrorMode) throws(ViceroyError) -> String {
            try runDecode(SingleByteDecoder(tableIndex: 2), bytes, mode, stripBOM: false)
        }

        public static func encode(_ string: String, mode: EncodingErrorMode) throws(ViceroyError) -> [UInt8] {
            try runEncode(SingleByteEncoder(tableIndex: 2), string.unicodeScalars, mode)
        }
    }

    /// ISO-8859-4, resolved statically — links only the single-byte tables.
    public enum ISO8859_4: TextEncoding {
        public static var name: String { "ISO-8859-4" }

        public static func decode(_ bytes: [UInt8], mode: DecodingErrorMode) throws(ViceroyError) -> String {
            try runDecode(SingleByteDecoder(tableIndex: 3), bytes, mode, stripBOM: false)
        }

        public static func encode(_ string: String, mode: EncodingErrorMode) throws(ViceroyError) -> [UInt8] {
            try runEncode(SingleByteEncoder(tableIndex: 3), string.unicodeScalars, mode)
        }
    }

    /// ISO-8859-5, resolved statically — links only the single-byte tables.
    public enum ISO8859_5: TextEncoding {
        public static var name: String { "ISO-8859-5" }

        public static func decode(_ bytes: [UInt8], mode: DecodingErrorMode) throws(ViceroyError) -> String {
            try runDecode(SingleByteDecoder(tableIndex: 4), bytes, mode, stripBOM: false)
        }

        public static func encode(_ string: String, mode: EncodingErrorMode) throws(ViceroyError) -> [UInt8] {
            try runEncode(SingleByteEncoder(tableIndex: 4), string.unicodeScalars, mode)
        }
    }

    /// ISO-8859-6, resolved statically — links only the single-byte tables.
    public enum ISO8859_6: TextEncoding {
        public static var name: String { "ISO-8859-6" }

        public static func decode(_ bytes: [UInt8], mode: DecodingErrorMode) throws(ViceroyError) -> String {
            try runDecode(SingleByteDecoder(tableIndex: 5), bytes, mode, stripBOM: false)
        }

        public static func encode(_ string: String, mode: EncodingErrorMode) throws(ViceroyError) -> [UInt8] {
            try runEncode(SingleByteEncoder(tableIndex: 5), string.unicodeScalars, mode)
        }
    }

    /// ISO-8859-7, resolved statically — links only the single-byte tables.
    public enum ISO8859_7: TextEncoding {
        public static var name: String { "ISO-8859-7" }

        public static func decode(_ bytes: [UInt8], mode: DecodingErrorMode) throws(ViceroyError) -> String {
            try runDecode(SingleByteDecoder(tableIndex: 6), bytes, mode, stripBOM: false)
        }

        public static func encode(_ string: String, mode: EncodingErrorMode) throws(ViceroyError) -> [UInt8] {
            try runEncode(SingleByteEncoder(tableIndex: 6), string.unicodeScalars, mode)
        }
    }

    /// ISO-8859-8, resolved statically — links only the single-byte tables.
    public enum ISO8859_8: TextEncoding {
        public static var name: String { "ISO-8859-8" }

        public static func decode(_ bytes: [UInt8], mode: DecodingErrorMode) throws(ViceroyError) -> String {
            try runDecode(SingleByteDecoder(tableIndex: 7), bytes, mode, stripBOM: false)
        }

        public static func encode(_ string: String, mode: EncodingErrorMode) throws(ViceroyError) -> [UInt8] {
            try runEncode(SingleByteEncoder(tableIndex: 7), string.unicodeScalars, mode)
        }
    }

    /// ISO-8859-8-I, resolved statically — links only the single-byte tables.
    public enum ISO8859_8I: TextEncoding {
        public static var name: String { "ISO-8859-8-I" }

        public static func decode(_ bytes: [UInt8], mode: DecodingErrorMode) throws(ViceroyError) -> String {
            try runDecode(SingleByteDecoder(tableIndex: 8), bytes, mode, stripBOM: false)
        }

        public static func encode(_ string: String, mode: EncodingErrorMode) throws(ViceroyError) -> [UInt8] {
            try runEncode(SingleByteEncoder(tableIndex: 8), string.unicodeScalars, mode)
        }
    }

    /// ISO-8859-10, resolved statically — links only the single-byte tables.
    public enum ISO8859_10: TextEncoding {
        public static var name: String { "ISO-8859-10" }

        public static func decode(_ bytes: [UInt8], mode: DecodingErrorMode) throws(ViceroyError) -> String {
            try runDecode(SingleByteDecoder(tableIndex: 9), bytes, mode, stripBOM: false)
        }

        public static func encode(_ string: String, mode: EncodingErrorMode) throws(ViceroyError) -> [UInt8] {
            try runEncode(SingleByteEncoder(tableIndex: 9), string.unicodeScalars, mode)
        }
    }

    /// ISO-8859-13, resolved statically — links only the single-byte tables.
    public enum ISO8859_13: TextEncoding {
        public static var name: String { "ISO-8859-13" }

        public static func decode(_ bytes: [UInt8], mode: DecodingErrorMode) throws(ViceroyError) -> String {
            try runDecode(SingleByteDecoder(tableIndex: 10), bytes, mode, stripBOM: false)
        }

        public static func encode(_ string: String, mode: EncodingErrorMode) throws(ViceroyError) -> [UInt8] {
            try runEncode(SingleByteEncoder(tableIndex: 10), string.unicodeScalars, mode)
        }
    }

    /// ISO-8859-14, resolved statically — links only the single-byte tables.
    public enum ISO8859_14: TextEncoding {
        public static var name: String { "ISO-8859-14" }

        public static func decode(_ bytes: [UInt8], mode: DecodingErrorMode) throws(ViceroyError) -> String {
            try runDecode(SingleByteDecoder(tableIndex: 11), bytes, mode, stripBOM: false)
        }

        public static func encode(_ string: String, mode: EncodingErrorMode) throws(ViceroyError) -> [UInt8] {
            try runEncode(SingleByteEncoder(tableIndex: 11), string.unicodeScalars, mode)
        }
    }

    /// ISO-8859-15, resolved statically — links only the single-byte tables.
    public enum ISO8859_15: TextEncoding {
        public static var name: String { "ISO-8859-15" }

        public static func decode(_ bytes: [UInt8], mode: DecodingErrorMode) throws(ViceroyError) -> String {
            try runDecode(SingleByteDecoder(tableIndex: 12), bytes, mode, stripBOM: false)
        }

        public static func encode(_ string: String, mode: EncodingErrorMode) throws(ViceroyError) -> [UInt8] {
            try runEncode(SingleByteEncoder(tableIndex: 12), string.unicodeScalars, mode)
        }
    }

    /// ISO-8859-16, resolved statically — links only the single-byte tables.
    public enum ISO8859_16: TextEncoding {
        public static var name: String { "ISO-8859-16" }

        public static func decode(_ bytes: [UInt8], mode: DecodingErrorMode) throws(ViceroyError) -> String {
            try runDecode(SingleByteDecoder(tableIndex: 13), bytes, mode, stripBOM: false)
        }

        public static func encode(_ string: String, mode: EncodingErrorMode) throws(ViceroyError) -> [UInt8] {
            try runEncode(SingleByteEncoder(tableIndex: 13), string.unicodeScalars, mode)
        }
    }

    /// KOI8-R, resolved statically — links only the single-byte tables.
    public enum KOI8R: TextEncoding {
        public static var name: String { "KOI8-R" }

        public static func decode(_ bytes: [UInt8], mode: DecodingErrorMode) throws(ViceroyError) -> String {
            try runDecode(SingleByteDecoder(tableIndex: 14), bytes, mode, stripBOM: false)
        }

        public static func encode(_ string: String, mode: EncodingErrorMode) throws(ViceroyError) -> [UInt8] {
            try runEncode(SingleByteEncoder(tableIndex: 14), string.unicodeScalars, mode)
        }
    }

    /// KOI8-U, resolved statically — links only the single-byte tables.
    public enum KOI8U: TextEncoding {
        public static var name: String { "KOI8-U" }

        public static func decode(_ bytes: [UInt8], mode: DecodingErrorMode) throws(ViceroyError) -> String {
            try runDecode(SingleByteDecoder(tableIndex: 15), bytes, mode, stripBOM: false)
        }

        public static func encode(_ string: String, mode: EncodingErrorMode) throws(ViceroyError) -> [UInt8] {
            try runEncode(SingleByteEncoder(tableIndex: 15), string.unicodeScalars, mode)
        }
    }

    /// macintosh, resolved statically — links only the single-byte tables.
    public enum Macintosh: TextEncoding {
        public static var name: String { "macintosh" }

        public static func decode(_ bytes: [UInt8], mode: DecodingErrorMode) throws(ViceroyError) -> String {
            try runDecode(SingleByteDecoder(tableIndex: 16), bytes, mode, stripBOM: false)
        }

        public static func encode(_ string: String, mode: EncodingErrorMode) throws(ViceroyError) -> [UInt8] {
            try runEncode(SingleByteEncoder(tableIndex: 16), string.unicodeScalars, mode)
        }
    }

    /// windows-874, resolved statically — links only the single-byte tables.
    public enum Windows874: TextEncoding {
        public static var name: String { "windows-874" }

        public static func decode(_ bytes: [UInt8], mode: DecodingErrorMode) throws(ViceroyError) -> String {
            try runDecode(SingleByteDecoder(tableIndex: 17), bytes, mode, stripBOM: false)
        }

        public static func encode(_ string: String, mode: EncodingErrorMode) throws(ViceroyError) -> [UInt8] {
            try runEncode(SingleByteEncoder(tableIndex: 17), string.unicodeScalars, mode)
        }
    }

    /// windows-1250, resolved statically — links only the single-byte tables.
    public enum Windows1250: TextEncoding {
        public static var name: String { "windows-1250" }

        public static func decode(_ bytes: [UInt8], mode: DecodingErrorMode) throws(ViceroyError) -> String {
            try runDecode(SingleByteDecoder(tableIndex: 18), bytes, mode, stripBOM: false)
        }

        public static func encode(_ string: String, mode: EncodingErrorMode) throws(ViceroyError) -> [UInt8] {
            try runEncode(SingleByteEncoder(tableIndex: 18), string.unicodeScalars, mode)
        }
    }

    /// windows-1251, resolved statically — links only the single-byte tables.
    public enum Windows1251: TextEncoding {
        public static var name: String { "windows-1251" }

        public static func decode(_ bytes: [UInt8], mode: DecodingErrorMode) throws(ViceroyError) -> String {
            try runDecode(SingleByteDecoder(tableIndex: 19), bytes, mode, stripBOM: false)
        }

        public static func encode(_ string: String, mode: EncodingErrorMode) throws(ViceroyError) -> [UInt8] {
            try runEncode(SingleByteEncoder(tableIndex: 19), string.unicodeScalars, mode)
        }
    }

    /// windows-1252, resolved statically — links only the single-byte tables.
    public enum Windows1252: TextEncoding {
        public static var name: String { "windows-1252" }

        public static func decode(_ bytes: [UInt8], mode: DecodingErrorMode) throws(ViceroyError) -> String {
            try runDecode(SingleByteDecoder(tableIndex: 20), bytes, mode, stripBOM: false)
        }

        public static func encode(_ string: String, mode: EncodingErrorMode) throws(ViceroyError) -> [UInt8] {
            try runEncode(SingleByteEncoder(tableIndex: 20), string.unicodeScalars, mode)
        }
    }

    /// windows-1253, resolved statically — links only the single-byte tables.
    public enum Windows1253: TextEncoding {
        public static var name: String { "windows-1253" }

        public static func decode(_ bytes: [UInt8], mode: DecodingErrorMode) throws(ViceroyError) -> String {
            try runDecode(SingleByteDecoder(tableIndex: 21), bytes, mode, stripBOM: false)
        }

        public static func encode(_ string: String, mode: EncodingErrorMode) throws(ViceroyError) -> [UInt8] {
            try runEncode(SingleByteEncoder(tableIndex: 21), string.unicodeScalars, mode)
        }
    }

    /// windows-1254, resolved statically — links only the single-byte tables.
    public enum Windows1254: TextEncoding {
        public static var name: String { "windows-1254" }

        public static func decode(_ bytes: [UInt8], mode: DecodingErrorMode) throws(ViceroyError) -> String {
            try runDecode(SingleByteDecoder(tableIndex: 22), bytes, mode, stripBOM: false)
        }

        public static func encode(_ string: String, mode: EncodingErrorMode) throws(ViceroyError) -> [UInt8] {
            try runEncode(SingleByteEncoder(tableIndex: 22), string.unicodeScalars, mode)
        }
    }

    /// windows-1255, resolved statically — links only the single-byte tables.
    public enum Windows1255: TextEncoding {
        public static var name: String { "windows-1255" }

        public static func decode(_ bytes: [UInt8], mode: DecodingErrorMode) throws(ViceroyError) -> String {
            try runDecode(SingleByteDecoder(tableIndex: 23), bytes, mode, stripBOM: false)
        }

        public static func encode(_ string: String, mode: EncodingErrorMode) throws(ViceroyError) -> [UInt8] {
            try runEncode(SingleByteEncoder(tableIndex: 23), string.unicodeScalars, mode)
        }
    }

    /// windows-1256, resolved statically — links only the single-byte tables.
    public enum Windows1256: TextEncoding {
        public static var name: String { "windows-1256" }

        public static func decode(_ bytes: [UInt8], mode: DecodingErrorMode) throws(ViceroyError) -> String {
            try runDecode(SingleByteDecoder(tableIndex: 24), bytes, mode, stripBOM: false)
        }

        public static func encode(_ string: String, mode: EncodingErrorMode) throws(ViceroyError) -> [UInt8] {
            try runEncode(SingleByteEncoder(tableIndex: 24), string.unicodeScalars, mode)
        }
    }

    /// windows-1257, resolved statically — links only the single-byte tables.
    public enum Windows1257: TextEncoding {
        public static var name: String { "windows-1257" }

        public static func decode(_ bytes: [UInt8], mode: DecodingErrorMode) throws(ViceroyError) -> String {
            try runDecode(SingleByteDecoder(tableIndex: 25), bytes, mode, stripBOM: false)
        }

        public static func encode(_ string: String, mode: EncodingErrorMode) throws(ViceroyError) -> [UInt8] {
            try runEncode(SingleByteEncoder(tableIndex: 25), string.unicodeScalars, mode)
        }
    }

    /// windows-1258, resolved statically — links only the single-byte tables.
    public enum Windows1258: TextEncoding {
        public static var name: String { "windows-1258" }

        public static func decode(_ bytes: [UInt8], mode: DecodingErrorMode) throws(ViceroyError) -> String {
            try runDecode(SingleByteDecoder(tableIndex: 26), bytes, mode, stripBOM: false)
        }

        public static func encode(_ string: String, mode: EncodingErrorMode) throws(ViceroyError) -> [UInt8] {
            try runEncode(SingleByteEncoder(tableIndex: 26), string.unicodeScalars, mode)
        }
    }

    /// x-mac-cyrillic, resolved statically — links only the single-byte tables.
    public enum XMacCyrillic: TextEncoding {
        public static var name: String { "x-mac-cyrillic" }

        public static func decode(_ bytes: [UInt8], mode: DecodingErrorMode) throws(ViceroyError) -> String {
            try runDecode(SingleByteDecoder(tableIndex: 27), bytes, mode, stripBOM: false)
        }

        public static func encode(_ string: String, mode: EncodingErrorMode) throws(ViceroyError) -> [UInt8] {
            try runEncode(SingleByteEncoder(tableIndex: 27), string.unicodeScalars, mode)
        }
    }

}

#endif
