//===----------------------------------------------------------------------===//
// viceroy-tablegen — regenerates Sources/Viceroy/Tables/*.swift from the
// vendored WHATWG index files. Dev-only; NOT part of the shipping library, so
// it may use Foundation. Run:
//
//     swift run viceroy-tablegen [vendorDir] [outDir]
//
// Defaults resolve relative to this source file, so a bare `swift run
// viceroy-tablegen` regenerates in place with no arguments and no network.
//===----------------------------------------------------------------------===//

import Foundation

// MARK: - Paths

let thisFile = URL(fileURLWithPath: #filePath)
let repoRoot = thisFile
    .deletingLastPathComponent()   // viceroy-tablegen/
    .deletingLastPathComponent()   // Tools/
    .deletingLastPathComponent()   // repo root
let args = CommandLine.arguments
let vendorDir = args.count > 1 ? URL(fileURLWithPath: args[1])
                               : repoRoot.appendingPathComponent("vendor/whatwg")
let outDir = args.count > 2 ? URL(fileURLWithPath: args[2])
                            : repoRoot.appendingPathComponent("Sources/Viceroy/Tables")

try? FileManager.default.createDirectory(at: outDir, withIntermediateDirectories: true)

func vendor(_ name: String) -> String {
    let url = vendorDir.appendingPathComponent(name)
    guard let s = try? String(contentsOf: url, encoding: .utf8) else {
        FileHandle.standardError.write("error: cannot read \(url.path)\n".data(using: .utf8)!)
        exit(1)
    }
    return s
}

// MARK: - Index-file parsing

/// Parse an `index-*.txt` file to `[(pointer, codePoint)]`.
func parseIndex(_ text: String) -> [(Int, UInt32)] {
    var out: [(Int, UInt32)] = []
    // `.isNewline` — robust to a CRLF checkout (`\r\n` is one Swift Character).
    for raw in text.split(whereSeparator: \.isNewline) {
        let line = raw.trimmingCharacters(in: .whitespacesAndNewlines)
        if line.isEmpty || line.hasPrefix("#") { continue }
        let parts = line.split(whereSeparator: { $0 == " " || $0 == "\t" }).map(String.init)
        guard parts.count >= 2, let ptr = Int(parts[0]) else { continue }
        let hex = parts[1].hasPrefix("0x") ? String(parts[1].dropFirst(2)) : parts[1]
        guard let cp = UInt32(hex, radix: 16) else { continue }
        out.append((ptr, cp))
    }
    return out
}

/// Dense pointer-indexed table (length = maxPointer + 1), `sentinel` for gaps.
func denseTable(_ entries: [(Int, UInt32)], sentinel: UInt32) -> [UInt32] {
    let maxPtr = entries.map(\.0).max() ?? -1
    var t = [UInt32](repeating: sentinel, count: maxPtr + 1)
    for (p, cp) in entries { t[p] = cp }
    return t
}

// MARK: - base64 packing (big-endian)

func packU16(_ table: [UInt32]) -> String {
    var bytes = [UInt8](); bytes.reserveCapacity(table.count * 2)
    for v in table {
        precondition(v <= 0xFFFF || v == 0xFFFF_FFFF)
        let u = v == 0xFFFF_FFFF ? UInt16(0xFFFF) : UInt16(v)
        bytes.append(UInt8(u >> 8)); bytes.append(UInt8(u & 0xFF))
    }
    return Data(bytes).base64EncodedString()
}
func packU32(_ table: [UInt32]) -> String {
    var bytes = [UInt8](); bytes.reserveCapacity(table.count * 4)
    for v in table {
        bytes.append(UInt8((v >> 24) & 0xFF)); bytes.append(UInt8((v >> 16) & 0xFF))
        bytes.append(UInt8((v >> 8) & 0xFF));  bytes.append(UInt8(v & 0xFF))
    }
    return Data(bytes).base64EncodedString()
}

let header = """
//===----------------------------------------------------------------------===//
// GENERATED by viceroy-tablegen from vendor/whatwg — DO NOT EDIT BY HAND.
// Regenerate with: swift run viceroy-tablegen
//===----------------------------------------------------------------------===//

"""

/// Emit a generated file. `trait` wraps the body in `#if <trait>` so that a
/// consumer who disables that family never compiles the table data in — the
/// base64 blobs are string literals, and an unreferenced literal still occupies
/// the binary, so exclusion has to happen at compile time, not link time.
func write(_ name: String, _ contents: String, trait: String? = nil) {
    let url = outDir.appendingPathComponent(name)
    let body = trait.map { "#if \($0)\n\(contents)\n#endif\n" } ?? contents
    try! (header + body).write(to: url, atomically: true, encoding: .utf8)
    print("wrote \(name)\(trait.map { "  [#if \($0)]" } ?? "")")
}

// MARK: - Single-byte tables + registry

// Canonical name  ->  index-file stem. Order defines the `.singleByte(N)` index
// and MUST match the statics in Encoding.swift.
// `type` is the Swift name of the static namespace (`Encoding.Windows1252`),
// spelled explicitly rather than derived, so it can never drift.
let singleByte: [(name: String, file: String, type: String)] = [
    ("IBM866", "ibm866", "IBM866"),
    ("ISO-8859-2", "iso-8859-2", "ISO8859_2"), ("ISO-8859-3", "iso-8859-3", "ISO8859_3"),
    ("ISO-8859-4", "iso-8859-4", "ISO8859_4"), ("ISO-8859-5", "iso-8859-5", "ISO8859_5"),
    ("ISO-8859-6", "iso-8859-6", "ISO8859_6"), ("ISO-8859-7", "iso-8859-7", "ISO8859_7"),
    ("ISO-8859-8", "iso-8859-8", "ISO8859_8"), ("ISO-8859-8-I", "iso-8859-8", "ISO8859_8I"),
    ("ISO-8859-10", "iso-8859-10", "ISO8859_10"), ("ISO-8859-13", "iso-8859-13", "ISO8859_13"),
    ("ISO-8859-14", "iso-8859-14", "ISO8859_14"), ("ISO-8859-15", "iso-8859-15", "ISO8859_15"),
    ("ISO-8859-16", "iso-8859-16", "ISO8859_16"),
    ("KOI8-R", "koi8-r", "KOI8R"), ("KOI8-U", "koi8-u", "KOI8U"),
    ("macintosh", "macintosh", "Macintosh"),
    ("windows-874", "windows-874", "Windows874"),
    ("windows-1250", "windows-1250", "Windows1250"), ("windows-1251", "windows-1251", "Windows1251"),
    ("windows-1252", "windows-1252", "Windows1252"), ("windows-1253", "windows-1253", "Windows1253"),
    ("windows-1254", "windows-1254", "Windows1254"), ("windows-1255", "windows-1255", "Windows1255"),
    ("windows-1256", "windows-1256", "Windows1256"), ("windows-1257", "windows-1257", "Windows1257"),
    ("windows-1258", "windows-1258", "Windows1258"),
    ("x-mac-cyrillic", "x-mac-cyrillic", "XMacCyrillic"),
]

var sbTablesSrc = "let _singleByteTables: [[UInt16]] = [\n"
for (i, sb) in singleByte.enumerated() {
    let entries = parseIndex(vendor("index-\(sb.file).txt"))
    var t = [UInt16](repeating: 0xFFFF, count: 128)
    for (p, cp) in entries {
        precondition(p >= 0 && p < 128, "single-byte pointer out of range in \(sb.file)")
        precondition(cp <= 0xFFFF && cp != 0xFFFF, "single-byte cp out of UInt16 / hits sentinel in \(sb.file)")
        t[p] = UInt16(cp)
    }
    let nums = t.map { "0x\(String($0, radix: 16, uppercase: true))" }.joined(separator: ",")
    sbTablesSrc += "  /* \(i) \(sb.name) */ [\(nums)],\n"
}
sbTablesSrc += "]\n\n"
sbTablesSrc += "let _singleByteNames: [String] = [\n  "
sbTablesSrc += singleByte.map { "\"\($0.name)\"" }.joined(separator: ", ")
sbTablesSrc += "\n]\n"
write("SingleByteTables.swift", sbTablesSrc, trait: "SingleByte")

// Static per-encoding namespaces for the single-byte family. All 28 share one
// small table array, so co-locating them in a single file costs nothing.
var sbEncSrc = "extension Encoding {\n"
for (i, sb) in singleByte.enumerated() {
    sbEncSrc += """
        /// \(sb.name), resolved statically — links only the single-byte tables.
        public enum \(sb.type): TextEncoding {
            public static var name: String { "\(sb.name)" }

            public static func decode(_ bytes: [UInt8], mode: DecodingErrorMode) throws(ViceroyError) -> String {
                try runDecode(SingleByteDecoder(tableIndex: \(i)), bytes, mode, stripBOM: false)
            }

            public static func encode(_ string: String, mode: EncodingErrorMode) throws(ViceroyError) -> [UInt8] {
                try runEncode(SingleByteEncoder(tableIndex: \(i)), string.unicodeScalars, mode)
            }
        }


    """
}
sbEncSrc += "}\n"
write("SingleByteEncodings.swift", sbEncSrc, trait: "SingleByte")

// MARK: - Labels + encoding registry

struct Enc: Decodable { let labels: [String]; let name: String }
struct Group: Decodable { let heading: String; let encodings: [Enc] }
let groups = try! JSONDecoder().decode([Group].self, from: Data(contentsOf: vendorDir.appendingPathComponent("encodings.json")))

// Name -> Swift `Scheme` expression.
func schemeExpr(for name: String) -> String {
    if let idx = singleByte.firstIndex(where: { $0.name == name }) { return ".singleByte(\(idx))" }
    switch name {
    case "UTF-8": return ".utf8"
    case "UTF-16LE": return ".utf16le"
    case "UTF-16BE": return ".utf16be"
    case "Big5": return ".big5"
    case "EUC-JP": return ".eucJP"
    case "ISO-2022-JP": return ".iso2022JP"
    case "Shift_JIS": return ".shiftJIS"
    case "EUC-KR": return ".eucKR"
    case "GBK": return ".gbk"
    case "gb18030": return ".gb18030"
    case "replacement": return ".replacement"
    case "x-user-defined": return ".xUserDefined"
    default:
        FileHandle.standardError.write("error: no scheme for encoding \"\(name)\"\n".data(using: .utf8)!)
        exit(1)
    }
}

var names: [String] = []
var schemes: [String] = []
var labelPairs: [(String, Int)] = []
for group in groups {
    for enc in group.encodings {
        let id = names.count
        names.append(enc.name)
        schemes.append(schemeExpr(for: enc.name))
        for label in enc.labels { labelPairs.append((label, id)) }
    }
}

var labelsSrc = "let _canonicalNames: [String] = [\n"
labelsSrc += names.map { "  \"\($0)\"" }.joined(separator: ",\n")
labelsSrc += "\n]\n\n"
labelsSrc += "let _schemes: [Scheme] = [\n"
labelsSrc += schemes.map { "  \($0)" }.joined(separator: ",\n")
labelsSrc += "\n]\n\n"
// Label lookup ships as a byte-searchable ASCII table rather than a
// `[String: Int]`. Swift `String` hashing/equality is canonical-equivalence
// based, which drags the Unicode normalization tables
// (`libswiftUnicodeDataTables`) into every binary — fatal for Embedded Swift.
// WHATWG labels are pure ASCII, so a sorted blob + binary search needs none of it.
let sortedLabels = labelPairs.sorted { a, b in
    Array(a.0.utf8).lexicographicallyPrecedes(Array(b.0.utf8))
}
var blob = ""
var offsets: [Int] = [0]
var encIdx: [Int] = []
for (label, id) in sortedLabels {
    precondition(label.utf8.allSatisfy { $0 >= 0x20 && $0 < 0x7F && $0 != 0x22 && $0 != 0x5C },
                 "label is not printable-ASCII / needs escaping: \(label)")
    blob += label
    offsets.append(blob.utf8.count)
    encIdx.append(id)
}
labelsSrc += "/// All \(sortedLabels.count) WHATWG labels, ASCII, concatenated in ascending byte order.\n"
labelsSrc += "let _labelBlob: StaticString = \"\(blob)\"\n\n"
labelsSrc += "/// Start offset of each label in `_labelBlob` (count + 1 entries).\n"
labelsSrc += "let _labelOffsets: [UInt32] = [\n  "
labelsSrc += offsets.map(String.init).joined(separator: ", ")
labelsSrc += "\n]\n\n"
labelsSrc += "/// Encoding-registry index for each label, parallel to `_labelOffsets`.\n"
labelsSrc += "let _labelEncoding: [UInt16] = [\n  "
labelsSrc += encIdx.map(String.init).joined(separator: ", ")
labelsSrc += "\n]\n"
write("Labels.swift", labelsSrc)

// MARK: - Multibyte tables

func writeU16(_ file: String, _ symbol: String, _ index: String, trait: String? = nil) {
    let entries = parseIndex(vendor(index))
    let t = denseTable(entries, sentinel: 0xFFFF)
    let src = """
    let _\(symbol)_b64: StaticString = "\(packU16(t))"
    let _\(symbol)_count = \(t.count)

    """
    write(file, src, trait: trait)
}

func writeU32(_ file: String, _ symbol: String, _ index: String, trait: String? = nil) {
    let entries = parseIndex(vendor(index))
    let t = denseTable(entries, sentinel: 0xFFFF_FFFF)
    let src = """
    let _\(symbol)_b64: StaticString = "\(packU32(t))"
    let _\(symbol)_count = \(t.count)

    """
    write(file, src, trait: trait)
}

writeU16("JIS0208Data.swift", "jis0208", "index-jis0208.txt", trait: "Japanese")
writeU16("JIS0212Data.swift", "jis0212", "index-jis0212.txt", trait: "Japanese")
writeU16("EUCKRData.swift", "eucKR", "index-euc-kr.txt", trait: "Korean")
writeU16("GB18030Data.swift", "gb18030", "index-gb18030.txt", trait: "Chinese")
writeU32("Big5Data.swift", "big5", "index-big5.txt", trait: "Chinese")

// gb18030 ranges (small — plain arrays)
let rangesEntries = parseIndex(vendor("index-gb18030-ranges.txt"))
var rangesSrc = "let _gb18030RangesPointers: [UInt32] = [\n  "
rangesSrc += rangesEntries.map { "\($0.0)" }.joined(separator: ", ")
rangesSrc += "\n]\n\nlet _gb18030RangesCodePoints: [UInt32] = [\n  "
rangesSrc += rangesEntries.map { "0x\(String($0.1, radix: 16, uppercase: true))" }.joined(separator: ", ")
rangesSrc += "\n]\n"
write("GB18030Ranges.swift", rangesSrc, trait: "Chinese")

// ISO-2022-JP katakana (63 entries — half-width katakana → jis0208 code point,
// used only by the ISO-2022-JP encoder). Small → plain array.
let kata = denseTable(parseIndex(vendor("index-iso-2022-jp-katakana.txt")), sentinel: 0xFFFF)
var kataSrc = "let _iso2022jpKatakana: [UInt16] = [\n  "
kataSrc += kata.map { "0x\(String($0, radix: 16, uppercase: true))" }.joined(separator: ", ")
kataSrc += "\n]\n"
write("ISO2022JPKatakana.swift", kataSrc, trait: "Japanese")

print("done — \(names.count) encodings, \(labelPairs.count) labels")
