//===----------------------------------------------------------------------===//
// viceroy-tablegen — regenerates Sources/Viceroy/Tables/*.swift from the
// vendored WHATWG index files. Dev-only; NOT part of the shipping library, so
// it may use Foundation. Run:
//
//     swift run viceroy-tablegen [vendorDir] [outDir]
//
// Defaults resolve relative to this source file, so a bare `swift run
// viceroy-tablegen` regenerates in place with no arguments and no network.
//===----------------------------------------------------------------------===//

import Foundation

// MARK: - Paths

let thisFile = URL(fileURLWithPath: #filePath)
let repoRoot = thisFile
    .deletingLastPathComponent()   // viceroy-tablegen/
    .deletingLastPathComponent()   // Tools/
    .deletingLastPathComponent()   // repo root
let args = CommandLine.arguments
let vendorDir = args.count > 1 ? URL(fileURLWithPath: args[1])
                               : repoRoot.appendingPathComponent("vendor/whatwg")
let outDir = args.count > 2 ? URL(fileURLWithPath: args[2])
                            : repoRoot.appendingPathComponent("Sources/Viceroy/Tables")

try? FileManager.default.createDirectory(at: outDir, withIntermediateDirectories: true)

func vendor(_ name: String) -> String {
    let url = vendorDir.appendingPathComponent(name)
    guard let s = try? String(contentsOf: url, encoding: .utf8) else {
        FileHandle.standardError.write("error: cannot read \(url.path)\n".data(using: .utf8)!)
        exit(1)
    }
    return s
}

// MARK: - Index-file parsing

/// Parse an `index-*.txt` file to `[(pointer, codePoint)]`.
func parseIndex(_ text: String) -> [(Int, UInt32)] {
    var out: [(Int, UInt32)] = []
    // `.isNewline` — robust to a CRLF checkout (`\r\n` is one Swift Character).
    for raw in text.split(whereSeparator: \.isNewline) {
        let line = raw.trimmingCharacters(in: .whitespacesAndNewlines)
        if line.isEmpty || line.hasPrefix("#") { continue }
        let parts = line.split(whereSeparator: { $0 == " " || $0 == "\t" }).map(String.init)
        guard parts.count >= 2, let ptr = Int(parts[0]) else { continue }
        let hex = parts[1].hasPrefix("0x") ? String(parts[1].dropFirst(2)) : parts[1]
        guard let cp = UInt32(hex, radix: 16) else { continue }
        out.append((ptr, cp))
    }
    return out
}

/// Dense pointer-indexed table (length = maxPointer + 1), `sentinel` for gaps.
func denseTable(_ entries: [(Int, UInt32)], sentinel: UInt32) -> [UInt32] {
    let maxPtr = entries.map(\.0).max() ?? -1
    var t = [UInt32](repeating: sentinel, count: maxPtr + 1)
    for (p, cp) in entries { t[p] = cp }
    return t
}

// MARK: - base64 packing (big-endian)

func packU16(_ table: [UInt32]) -> String {
    var bytes = [UInt8](); bytes.reserveCapacity(table.count * 2)
    for v in table {
        precondition(v <= 0xFFFF || v == 0xFFFF_FFFF)
        let u = v == 0xFFFF_FFFF ? UInt16(0xFFFF) : UInt16(v)
        bytes.append(UInt8(u >> 8)); bytes.append(UInt8(u & 0xFF))
    }
    return Data(bytes).base64EncodedString()
}
func packU32(_ table: [UInt32]) -> String {
    var bytes = [UInt8](); bytes.reserveCapacity(table.count * 4)
    for v in table {
        bytes.append(UInt8((v >> 24) & 0xFF)); bytes.append(UInt8((v >> 16) & 0xFF))
        bytes.append(UInt8((v >> 8) & 0xFF));  bytes.append(UInt8(v & 0xFF))
    }
    return Data(bytes).base64EncodedString()
}

let header = """
//===----------------------------------------------------------------------===//
// GENERATED by viceroy-tablegen from vendor/whatwg — DO NOT EDIT BY HAND.
// Regenerate with: swift run viceroy-tablegen
//===----------------------------------------------------------------------===//

"""

func write(_ name: String, _ contents: String) {
    let url = outDir.appendingPathComponent(name)
    try! (header + contents).write(to: url, atomically: true, encoding: .utf8)
    print("wrote \(name)")
}

// MARK: - Single-byte tables + registry

// Canonical name  ->  index-file stem. Order defines the `.singleByte(N)` index
// and MUST match the statics in Encoding.swift.
let singleByte: [(name: String, file: String)] = [
    ("IBM866", "ibm866"),
    ("ISO-8859-2", "iso-8859-2"), ("ISO-8859-3", "iso-8859-3"), ("ISO-8859-4", "iso-8859-4"),
    ("ISO-8859-5", "iso-8859-5"), ("ISO-8859-6", "iso-8859-6"), ("ISO-8859-7", "iso-8859-7"),
    ("ISO-8859-8", "iso-8859-8"), ("ISO-8859-8-I", "iso-8859-8"),
    ("ISO-8859-10", "iso-8859-10"), ("ISO-8859-13", "iso-8859-13"), ("ISO-8859-14", "iso-8859-14"),
    ("ISO-8859-15", "iso-8859-15"), ("ISO-8859-16", "iso-8859-16"),
    ("KOI8-R", "koi8-r"), ("KOI8-U", "koi8-u"), ("macintosh", "macintosh"),
    ("windows-874", "windows-874"),
    ("windows-1250", "windows-1250"), ("windows-1251", "windows-1251"), ("windows-1252", "windows-1252"),
    ("windows-1253", "windows-1253"), ("windows-1254", "windows-1254"), ("windows-1255", "windows-1255"),
    ("windows-1256", "windows-1256"), ("windows-1257", "windows-1257"), ("windows-1258", "windows-1258"),
    ("x-mac-cyrillic", "x-mac-cyrillic"),
]

var sbTablesSrc = "let _singleByteTables: [[UInt16]] = [\n"
for (i, sb) in singleByte.enumerated() {
    let entries = parseIndex(vendor("index-\(sb.file).txt"))
    var t = [UInt16](repeating: 0xFFFF, count: 128)
    for (p, cp) in entries {
        precondition(p >= 0 && p < 128, "single-byte pointer out of range in \(sb.file)")
        precondition(cp <= 0xFFFF && cp != 0xFFFF, "single-byte cp out of UInt16 / hits sentinel in \(sb.file)")
        t[p] = UInt16(cp)
    }
    let nums = t.map { "0x\(String($0, radix: 16, uppercase: true))" }.joined(separator: ",")
    sbTablesSrc += "  /* \(i) \(sb.name) */ [\(nums)],\n"
}
sbTablesSrc += "]\n\n"
sbTablesSrc += "let _singleByteNames: [String] = [\n  "
sbTablesSrc += singleByte.map { "\"\($0.name)\"" }.joined(separator: ", ")
sbTablesSrc += "\n]\n"
write("SingleByteTables.swift", sbTablesSrc)

// MARK: - Labels + encoding registry

struct Enc: Decodable { let labels: [String]; let name: String }
struct Group: Decodable { let heading: String; let encodings: [Enc] }
let groups = try! JSONDecoder().decode([Group].self, from: Data(contentsOf: vendorDir.appendingPathComponent("encodings.json")))

// Name -> Swift `Scheme` expression.
func schemeExpr(for name: String) -> String {
    if let idx = singleByte.firstIndex(where: { $0.name == name }) { return ".singleByte(\(idx))" }
    switch name {
    case "UTF-8": return ".utf8"
    case "UTF-16LE": return ".utf16le"
    case "UTF-16BE": return ".utf16be"
    case "Big5": return ".big5"
    case "EUC-JP": return ".eucJP"
    case "ISO-2022-JP": return ".iso2022JP"
    case "Shift_JIS": return ".shiftJIS"
    case "EUC-KR": return ".eucKR"
    case "GBK": return ".gbk"
    case "gb18030": return ".gb18030"
    case "replacement": return ".replacement"
    case "x-user-defined": return ".xUserDefined"
    default:
        FileHandle.standardError.write("error: no scheme for encoding \"\(name)\"\n".data(using: .utf8)!)
        exit(1)
    }
}

var names: [String] = []
var schemes: [String] = []
var labelPairs: [(String, Int)] = []
for group in groups {
    for enc in group.encodings {
        let id = names.count
        names.append(enc.name)
        schemes.append(schemeExpr(for: enc.name))
        for label in enc.labels { labelPairs.append((label, id)) }
    }
}

var labelsSrc = "let _canonicalNames: [String] = [\n"
labelsSrc += names.map { "  \"\($0)\"" }.joined(separator: ",\n")
labelsSrc += "\n]\n\n"
labelsSrc += "let _schemes: [Scheme] = [\n"
labelsSrc += schemes.map { "  \($0)" }.joined(separator: ",\n")
labelsSrc += "\n]\n\n"
labelsSrc += "let _labelToIndex: [String: Int] = [\n"
labelsSrc += labelPairs.sorted { $0.0 < $1.0 }.map { "  \"\($0.0)\": \($0.1)" }.joined(separator: ",\n")
labelsSrc += "\n]\n"
write("Labels.swift", labelsSrc)

// MARK: - Multibyte tables

func writeU16(_ file: String, _ symbol: String, _ index: String) {
    let entries = parseIndex(vendor(index))
    let t = denseTable(entries, sentinel: 0xFFFF)
    let src = """
    let _\(symbol)_b64: StaticString = "\(packU16(t))"
    let _\(symbol)_count = \(t.count)

    """
    write(file, src)
}

func writeU32(_ file: String, _ symbol: String, _ index: String) {
    let entries = parseIndex(vendor(index))
    let t = denseTable(entries, sentinel: 0xFFFF_FFFF)
    let src = """
    let _\(symbol)_b64: StaticString = "\(packU32(t))"
    let _\(symbol)_count = \(t.count)

    """
    write(file, src)
}

writeU16("JIS0208Data.swift", "jis0208", "index-jis0208.txt")
writeU16("JIS0212Data.swift", "jis0212", "index-jis0212.txt")
writeU16("EUCKRData.swift", "eucKR", "index-euc-kr.txt")
writeU16("GB18030Data.swift", "gb18030", "index-gb18030.txt")
writeU32("Big5Data.swift", "big5", "index-big5.txt")

// gb18030 ranges (small — plain arrays)
let rangesEntries = parseIndex(vendor("index-gb18030-ranges.txt"))
var rangesSrc = "let _gb18030RangesPointers: [UInt32] = [\n  "
rangesSrc += rangesEntries.map { "\($0.0)" }.joined(separator: ", ")
rangesSrc += "\n]\n\nlet _gb18030RangesCodePoints: [UInt32] = [\n  "
rangesSrc += rangesEntries.map { "0x\(String($0.1, radix: 16, uppercase: true))" }.joined(separator: ", ")
rangesSrc += "\n]\n"
write("GB18030Ranges.swift", rangesSrc)

// ISO-2022-JP katakana (63 entries — half-width katakana → jis0208 code point,
// used only by the ISO-2022-JP encoder). Small → plain array.
let kata = denseTable(parseIndex(vendor("index-iso-2022-jp-katakana.txt")), sentinel: 0xFFFF)
var kataSrc = "let _iso2022jpKatakana: [UInt16] = [\n  "
kataSrc += kata.map { "0x\(String($0, radix: 16, uppercase: true))" }.joined(separator: ", ")
kataSrc += "\n]\n"
write("ISO2022JPKatakana.swift", kataSrc)

print("done — \(names.count) encodings, \(labelPairs.count) labels")
